In [28]:
def classify(row):
    if row['gsc_impressions'] > 20000 and row['ga_sessions'] < 100:
        return "High visibility / low engagement (Fix content)"
    elif row['ga_engagement_time'] > 30:
        return "High quality content"
    elif row['gsc_clicks'] > 100:
        return "High traffic driver"
    else:
        return "Normal"

page_metrics['category'] = page_metrics.apply(classify, axis=1)

page_metrics[['Page','category']]

                                            Page              category
0                         /blogs/paypal-in-nepal   High traffic driver
1                                          /zoom  High quality content
2     /blogs/zoom-not-working-troubleshoot-guide  High quality content
3     /blogs/aws-in-2026-latest-services-updates                Normal
4                     /cloud-consulting-in-nepal                Normal
..                                           ...                   ...
69                      /plans/zoom-webinar-plan                Normal
70         /faq/what-cloud-services-do-you-offer                Normal
71                                /cloud-service                Normal
72  /faq/how-secure-is-your-cloud-infrastructure                Normal
73                               /careers/test-4                Normal

[74 rows x 2 columns]

In [27]:
page_metrics['ctr'] = page_metrics['gsc_clicks'] / page_metrics['gsc_impressions']

page_metrics['click_to_session_ratio'] = page_metrics['ga_sessions'] / page_metrics['gsc_clicks']

page_metrics['engagement_efficiency'] = page_metrics['ga_engagement_time'] / page_metrics['ga_sessions']

page_metrics.head()

,Page,gsc_clicks,gsc_impressions,gsc_ctr,gsc_position,ga_sessions,ga_active_users,ga_new_users,ga_engagement_time,ga_conversions,Total revenue,Session key event rate,click_to_session_ratio,engagement_per_session,visibility_score,ctr,engagement_efficiency
0,/blogs/paypal-in-nepal,349,61503,0.0057,4.46,257,215,215,29.626459,0,0,0,0.736390,29.626459,350.5671,0.005675,0.115278
1,/zoom,107,4076,0.0263,11.57,65,62,59,74.030769,0,0,0,0.607477,74.030769,107.1988,0.026251,1.138935
2,/blogs/zoom-not-working-troubleshoot-guide,102,26600,0.0038,6.22,140,134,133,36.800000,0,0,0,1.372549,36.800000,101.0800,0.003835,0.262857
3,/blogs/aws-in-2026-latest-services-updates,29,80547,0.0004,6.44,592,525,524,17.701014,0,0,0,20.413793,17.701014,32.2188,0.000360,0.029900
4,/cloud-consulting-in-nepal,26,1431,0.0182,11.50,53,25,22,11.905660,0,0,0,2.038462,11.905660,26.0442,0.018169,0.224635

In [26]:
page_metrics.sort_values('ga_sessions', ascending=False)[
    ['Page', 'gsc_clicks', 'gsc_impressions', 'ga_sessions', 'ga_engagement_time']
].head(10)

,Page,gsc_clicks,gsc_impressions,ga_sessions,ga_engagement_time
3,/blogs/aws-in-2026-latest-services-updates,29,80547,592,17.701014
27,/blogs/simple-comparison-of-zoom-vs-discord,2,3203,338,14.482249
0,/blogs/paypal-in-nepal,349,61503,257,29.626459
14,/blogs/amazon-bedrock-aws-ai-platform-guide,9,49523,232,7.564655
2,/blogs/zoom-not-working-troubleshoot-guide,102,26600,140,36.800000
45,/cybersecurity,0,145,87,4.954023
13,/blogs/complete-guide-to-aws-database,10,10061,78,6.948718
15,/blogs/what-is-aws-guide-amazon-web-services,8,19555,74,28.337838
1,/zoom,107,4076,65,74.030769
4,/cloud-consulting-in-nepal,26,1431,53,11.905660

In [25]:
page_metrics['click_to_session_ratio'] = page_metrics['ga_sessions'] / page_metrics['gsc_clicks']
page_metrics['engagement_per_session'] = page_metrics['ga_engagement_time']
page_metrics['visibility_score'] = page_metrics['gsc_impressions'] * page_metrics['gsc_ctr']

In [24]:
page_metrics['gsc_ctr'] = page_metrics['gsc_ctr'].str.replace('%','').astype(float) / 100

In [23]:
page_metrics = page_metrics.copy()

page_metrics = page_metrics.rename(columns={
    'Clicks': 'gsc_clicks',
    'Impressions': 'gsc_impressions',
    'CTR': 'gsc_ctr',
    'Position': 'gsc_position',
    'Sessions': 'ga_sessions',
    'Active users': 'ga_active_users',
    'New users': 'ga_new_users',
    'Average engagement time per session': 'ga_engagement_time',
    'Key events': 'ga_conversions'
})

In [22]:
page_metrics = pd.merge(
    gsc_pages,
    ga4,
    on='Page',
    how='inner'
)

print(page_metrics.shape)
print(page_metrics.head())

(74, 12)
                                         Page  Clicks  Impressions    CTR  \
0                      /blogs/paypal-in-nepal     349        61503  0.57%
1                                       /zoom     107         4076  2.63%
2  /blogs/zoom-not-working-troubleshoot-guide     102        26600  0.38%
3  /blogs/aws-in-2026-latest-services-updates      29        80547  0.04%
4                  /cloud-consulting-in-nepal      26         1431  1.82%

   Position  Sessions  Active users  New users  \
0      4.46       257           215        215
1     11.57        65            62         59
2      6.22       140           134        133
3      6.44       592           525        524
4     11.50        53            25         22

   Average engagement time per session  Key events  Total revenue  \
0                            29.626459           0              0
1                            74.030769           0              0
2                            36.800000           0              0
3                            17.701014           0              0
4                            11.905660           0              0

   Session key event rate
0                       0
1                       0
2                       0
3                       0
4                       0

In [21]:
ga4 = ga4[ga4['Page'].str.startswith('/')]

In [20]:
ga4['Page'] = (
    ga4['Page']
    .astype(str)
    .str.lower()
    .str.strip()
    .str.replace(r'\(not set\)', '', regex=True)
    .str.rstrip('/')
)

In [19]:
gsc_pages['Page'] = (
    gsc_pages['Page']
    .str.lower()
    .str.replace(r'https?://[^/]+', '', regex=True)  # remove domain
    .str.rstrip('/')
    .str.strip()
)

In [18]:
page_metrics = pd.merge(
    gsc_pages,
    ga4,
    on='Page',
    how='inner'
)

print(page_metrics.shape)
print(page_metrics.head())

(75, 12)
                                         Page  Clicks  Impressions     CTR  \
0                                                 585         4435  13.19%
1                      /blogs/paypal-in-nepal     349        61503   0.57%
2                                       /zoom     107         4076   2.63%
3  /blogs/zoom-not-working-troubleshoot-guide     102        26600   0.38%
4  /blogs/aws-in-2026-latest-services-updates      29        80547   0.04%

   Position  Sessions  Active users  New users  \
0      5.27       572           470        465
1      4.46       257           215        215
2     11.57        65            62         59
3      6.22       140           134        133
4      6.44       592           525        524

   Average engagement time per session  Key events  Total revenue  \
0                            37.127622           0              0
1                            29.626459           0              0
2                            74.030769           0              0
3                            36.800000           0              0
4                            17.701014           0              0

   Session key event rate
0                       0
1                       0
2                       0
3                       0
4                       0

In [17]:
def clean_url(col):
    return (
        col.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(r'https?://[^/]+', '', regex=True)  # remove domain if exists
        .str.rstrip('/')  # remove trailing slash
    )

gsc_pages['Page'] = clean_url(gsc_pages['Page'])
ga4['Page'] = clean_url(ga4['Page'])

In [29]:
import re

def mask_url(series):
    return series.str.replace(r'https?://[^/]+', 'https://[client-site]', regex=True)

print("GSC sample pages:")
print(mask_url(gsc_pages['Page']).head(10))

print("\nGA4 sample pages:")
print(ga4['Page'].head(10))

GSC sample pages:
0
1                         /blogs/paypal-in-nepal
2                                          /zoom
3     /blogs/zoom-not-working-troubleshoot-guide
4     /blogs/aws-in-2026-latest-services-updates
5                     /cloud-consulting-in-nepal
6    /blogs/zoom-vs-microsoft-teams-for-business
7                                    /contact-us
8                                        /career
9                                    /zoom-nepal
Name: Page, dtype: str

GA4 sample pages:
0       /blogs/aws-in-2026-latest-services-updates
2      /blogs/simple-comparison-of-zoom-vs-discord
3                           /blogs/paypal-in-nepal
4      /blogs/amazon-bedrock-aws-ai-platform-guide
5       /blogs/zoom-not-working-troubleshoot-guide
7                                   /cybersecurity
8            /blogs/complete-guide-to-aws-database
9     /blogs/what-is-aws-guide-amazon-web-services
10                                           /zoom
11                      /cloud-consulting-in-nepal
Name: Page, dtype: str

In [15]:
page_metrics = pd.merge(
    gsc_pages,
    ga4,
    on='Page',
    how='inner'
)

print(page_metrics.head())
print(page_metrics.shape)

Empty DataFrame
Columns: [Page, Clicks, Impressions, CTR, Position, Sessions, Active users, New users, Average engagement time per session, Key events, Total revenue, Session key event rate]
Index: []
(0, 12)

In [14]:
gsc_pages['Page'] = gsc_pages['Page'].str.strip()
ga4['Page'] = ga4['Page'].str.strip()

In [13]:
gsc_pages = gsc_pages.rename(columns={
    'Top pages': 'Page'
})

In [12]:
# strip ALL column whitespace first
gsc_pages.columns = gsc_pages.columns.str.strip()
ga4.columns = ga4.columns.str.strip()

print("Cleaned GSC columns:", gsc_pages.columns)

Cleaned GSC columns: Index(['Top pages', 'Clicks', 'Impressions', 'CTR', 'Position'], dtype='str')

In [11]:
print("GSC PAGES COLUMNS:")
print(gsc_pages.columns)

print("\nGA4 COLUMNS:")
print(ga4.columns)

GSC PAGES COLUMNS:
Index(['Top pages', 'Clicks', 'Impressions', 'CTR', 'Position'], dtype='str')

GA4 COLUMNS:
Index(['Page', 'Sessions', 'Active users', 'New users',
       'Average engagement time per session', 'Key events', 'Total revenue',
       'Session key event rate'],
      dtype='str')

In [9]:
gsc_pages.columns = gsc_pages.columns.str.strip()
gsc_queries.columns = gsc_queries.columns.str.strip()
ga4.columns = ga4.columns.str.strip()

# Normalize key column names
gsc_pages.rename(columns={'Page': 'Page'}, inplace=True)
ga4.rename(columns={'Landing page': 'Page'}, inplace=True)

In [8]:
file_path = '../data/ga4_landing_page.csv'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

header_index = None
for i, line in enumerate(lines):
    if line.startswith("Landing page"):
        header_index = i
        break

print("GA4 header found at line:", header_index)

ga4 = pd.read_csv(file_path, skiprows=header_index)

print(ga4.head())

GA4 header found at line: 9
                                  Landing page  Sessions  Active users  \
0   /blogs/aws-in-2026-latest-services-updates       592           525
1                                            /       572           470
2  /blogs/simple-comparison-of-zoom-vs-discord       338           337
3                       /blogs/paypal-in-nepal       257           215
4  /blogs/amazon-bedrock-aws-ai-platform-guide       232           222

   New users  Average engagement time per session  Key events  Total revenue  \
0        524                            17.701014           0              0
1        465                            37.127622           0              0
2        337                            14.482249           0              0
3        215                            29.626459           0              0
4        222                             7.564655           0              0

   Session key event rate
0                       0
1                       0
2                       0
3                       0
4                       0

In [6]:
import pandas as pd